# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#                                           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

even_fib_sum = 0
fib_first = 1
fib_second = 2

while fib_second < 4_000_000
  even_fib_sum += fib_second if fib_second.even?
  fib_second += fib_first
  fib_first = fib_second - fib_first
end

p even_fib_sum
